### ISSUE TITLE
devise pull 後に、「Could not find proper version of railties (6.1.7) in any of the sources」が発生してrailsコマンドが入力できない

### ISSUE THREAD

**Issue by tsuyoron** [takomomo202208/git-nagano-cafeVer1.0#13]
### 詳細：
最新の、developをpullしたのですが「Could not find proper version of railties (6.1.7) in any of the sources」が発生してrailsコマンドが入力できないです。
訳すとこんな感じ「いずれのソースにも適切なバージョンの railties (6.1.7) が見つかりませんでした」

### 不明点：
・railtiesのバージョンを何に統一させるのか認識ができていない
→とりあえず、バージョン(6.1.7)に合わせる認識でよいでしょうか？(  `rails -v` 実行時に、 `Rails 6.1.7` が表示されたらOKの認識)
・エラーを解消するための、バージョンの追加/変更方法を教えていただきたいです。

**Comment by tsuyoron** [comment]
[・エラーを解消するための、バージョンの追加/変更方法を教えていただきたいです。](https://stackoverflow.com/questions/37117230/rails-new-gives-could-not-find-proper-version-of-railties-4-2-5-1-in-any-of-t
)
については、以下の作業を実施することで解決しました。
Run `gem update rails` first, then `bundle update`

**Comment by aboutyasui** [comment]
確認したところバージョンは6.1.7でした

**Comment by tsuyoron** [comment]
こちらの問題については、本日のデイリースクラムで共有後Closeします！！
