### ISSUE TITLE
net-smtpのinstallについて作業に追加する必要がある

### ISSUE THREAD

**Issue by tsuyoron** [takomomo202208/git-nagano-cafeVer1.0#14]
### 詳細：
devise配下でコマンド実行時に、「You don't have net-smtp installed in your application. Please add it to your Gemfile and run bundle install」が表示されました。

### 不明点：
・WBSにも記載がないため、だれがダウンロードするか決めた方がいいと思います。

### net-smtpのinstallのインストール方法
1. Gemfile上で以下を追加
~~~:Gemfile
gem 'net-smtp' 
~~~
2. Console上で以下を実行
~~~:Console
bundle install 
~~~

**Comment by aboutyasui** [comment]
すいません。
それ今度のマージで追加予定でした(;^ω^)
連絡忘れてました！すいませんm(__)m

**Comment by tsuyoron** [comment]
こちらの問題については、本日のデイリースクラムで共有後Closeします！！
