### ISSUE TITLE
hint: You have divergent branches and need to specify how to reconcile them.

### ISSUE THREAD

**Issue by tsuyoron** [takomomo202208/git-nagano-cafeVer1.0#27]
問題：
「hint: You have divergent branches and need to specify how to reconcile them.」と表示され、git pullの処理ができない

**Comment by tsuyoron** [comment]
*  `git pull --rebase` を実行することで解決いたします。
→rebaseされるため、コミットが異なる場合がある

* `git branch -D` で一旦branchを削除することで解消

原因については良く分かってないので分かる方がいたら教えていただきたいです。

**Comment by aboutyasui** [comment]
これって作業の流れとしては、以下の感じですか？
①作業用branchで編集・追加等の作業をする
②他のbranchへ移動(checkout)を試みる

**Comment by YK2022-July** [comment]
確認したのでCloseします。
