### ISSUE TITLE
routesに関して、resources を利用してほしい

### ISSUE THREAD

**Issue by tsuyoron** [takomomo202208/git-nagano-cafeVer1.0#39]
routesに関して、resources を利用して記載をしていただきたいですm(__)m
・as:'edit_my_page'　などの指定が随時必要になる
・間違えが発生しやすくなる

**Comment by aboutyasui** [comment]
一応間違っていた箇所に関しては直してましたけど、それでもまだ間違っていましたでしょうか？

**Comment by aboutyasui** [comment]
変更完了しました！！
時間ある時で構いませんので、ご確認お願い致します！！

※ご迷惑をお掛けしました(ノД`)・゜・。

**Comment by tsuyoron** [comment]
このサイト分かりやすかったです👍
https://pikawaka.com/rails/resources

**Comment by aboutyasui** [comment]
それ見やすいですよね(/・ω・)/
（応用課題のときに見てましたｗ）
