### ISSUE TITLE
ログイン画面が表示できなかった問題について

### ISSUE THREAD

**Issue by aboutyasui** [takomomo202208/git-nagano-cafeVer1.0#40]
問題について
・topページからログインページに遷移した際エラー発生
エラーについて
`uninitialized constant User`
→`uninitialized constant`は「定義したクラスを読むことができない」
考えられる原因
・ルートの記述に不備（今回はこれが原因でした）
・コントローラのクラス名に不備
・テンプレートのViewファイルが存在しない
~~~
devise_for :customers,skip: [:passwords],controllers: {
    sessions:     'admins/sessions',
    registrations: 'admins/registrations'
  }
~~~
のところを
~~~
devise_for :customers,skip: [:passwords],controllers: {
    sessions:     'public/sessions',
    registrations: 'public/registrations'
  }
~~~
に変更（adminも同様に変更）

**Comment by aboutyasui** [comment]
ブラウザにてリロードを実行した際に次のエラーが発生
`ArgumentError in Customer::Registrations#new`

エラーについて
・メソッドの引数が正しくない時や足りない時に発生するエラーです。
参考記事：https://diveintocode.jp/blogs/Technology/ErrorCollection

**Comment by aboutyasui** [comment]
全員に共有後closeします～

**Comment by tsuyoron** [comment]
確認したためCloseいたします
