### ISSUE TITLE
サインイン後のページが表示されない問題

### ISSUE THREAD

**Issue by aboutyasui** [takomomo202208/git-nagano-cafeVer1.0#45]
事の経緯
①Topページよりサインインを行う
②先程まで正常に動いて部分にエラー（部分テンプレートのヘッダーに対してエラー）

エラーの内容
`ActionView::Template::Error (SQLite3::SQLException: no such column: customers.):`
→SQLなので**データに問題**があるかも

エラーの原因を追究してみる
①rails c実行
②Customer.allを実行
③サインイン時に作成したデータが見れる（customerだけね）
④主キーがないことに気付く

修正した点
主キーが作られてないことが発覚したので、migrateファイルを確認する
①customerのmigrateファイルを確認する
②`, id: false`こいつが悪さをしていたみたいです。
~~~
 def change
    create_table :customers , id: false do |t|
      ## Database authenticatable
~~~
を
~~~
def change
    create_table :customers do |t|
~~~
に変更

修正後にやること
①rails db:migrate:status→ダウン状態にしたいDBのVer番号を控える
②rails db:migrate:down VERTION=さっき控えた番号
　→もう一度「rails db:migrate:status」down状態を確認する
③rails db:migrate
④schema.rbを開き主キーが追加されていることを確認できればOK

**Comment by aboutyasui** [comment]
sing in後　ログアウトできなかった問題

問題について（ことの経緯）
先程のサインアップテストのあとログアウト操作を行ったところ
うまく操作ができなかった

原因
ブートストラップ関係で問題が生じているため（メンターさんより）

対処はカトゥーンさんがやってくれたので、
他のIssuesを参照してください。

※**ブートストラップに問題があるとログインログアウト機能にも反映されること**だけ認識お願い致します。

**Comment by aboutyasui** [comment]
共有後closeします〜

**Comment by tsuyoron** [comment]
[この問題](https://github.com/takomomo202208/git-nagano-cafeVer1.0/issues/51#issue-1381928936)と同じため、closeいたします。
