### ISSUE TITLE
sign_up操作時のSQLiteエラー

### ISSUE THREAD

**Issue by SayakaIw** [takomomo202208/git-nagano-cafeVer1.0#51]
ブラウザでsign_up動作を実施すると、「SQLite3::SQLException: no such column: customers.」のエラーが発生する。

原因：customerのdeviceのデータがエラーを起こしている。

解決：①rails db:migrate:status（エラーを起こしているmigrateファイルの番号を調べる）②rails db:migrate:down VERSION=①の番号  (downにすると、db内データ全部消える。追加のカラムもdownのうちに編集可）③rails db:migrate:up VERSION=↑番号
追記あれば、お願いします。

**Comment by tsuyoron** [comment]
内容について、問題なさそうなのでCloseいたします。
